"""
Emit dashboard/rules.generated.js from the Python configuration.

The browser has to score a defect without a server, which means the severity
bands, priority weights and routing table exist in JavaScript too. Rather than
retyping them (and letting them drift), this generates them from the same
config the Python engine reads. tests/test_js_parity.py then runs the JS under
node and asserts it agrees with roadlens.severity on thousands of inputs.
"""
from __future__ import annotations

import json
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from roadlens.config import get_config
from roadlens.dedup import MERGE_RADIUS_METERS, _merge_radius
from roadlens.severity import _severity_settings

OUT = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))),
                   "dashboard", "rules.generated.js")

levels, routing, default_dept = _severity_settings()
cfg = get_config()

payload = {
    "severityLevels": [list(row) for row in levels],
    "departmentRouting": routing,
    "defaultDepartment": default_dept,
    "mergeRadiusMeters": _merge_radius(),
    "confidenceThreshold": cfg.detector.confidence_threshold,
    "recurrenceRadiusMeters": cfg.predictive.recurrence_radius_meters,
}

js = f"""// GENERATED by tools/generate_rules_js.py — do not edit by hand.
// Mirrors roadlens/config.py + roadlens/severity.py so the browser can score a
// defect with no server. tests/test_js_parity.py runs assess() below under node
// and asserts it matches roadlens.severity.assess on random inputs.
export const RULES = {json.dumps(payload, indent=2)};

// Ported from roadlens/severity.py:assess — keep the two in step; the parity
// test will fail loudly if they drift.
export function assess(defectType, areaRatio, confidence, sightings) {{
  areaRatio = Math.max(0, Number(areaRatio) || 0);
  confidence = Math.min(Math.max(Number(confidence) || 0, 0), 1);
  sightings = Math.max(1, Math.trunc(Number(sightings) || 1));

  let band = RULES.severityLevels[RULES.severityLevels.length - 1];
  for (const row of RULES.severityLevels) {{
    if (areaRatio >= row[0]) {{ band = row; break; }}
  }}
  const [, level, label, slaHours, baseCost] = band;

  const size = Math.min(areaRatio / 0.08, 1.0) * 60;
  const conf = confidence * 25;
  const seen = (Math.min(sightings, 5) / 5) * 15;
  // Python's round() is banker's rounding; replicate it so the two agree on .5
  const raw = size + conf + seen;
  let priority = Math.round(raw);
  if (Math.abs(raw - Math.trunc(raw) - 0.5) < 1e-9) {{
    const fl = Math.floor(raw);
    priority = (fl % 2 === 0) ? fl : fl + 1;
  }}

  return {{
    severity_level: level,
    severity_label: label,
    priority_score: Math.min(priority, 100),
    est_cost_inr: Math.trunc(baseCost * (1 + Math.min(areaRatio * 4, 1.0))),
    sla_hours: slaHours,
    department: RULES.departmentRouting[defectType] || RULES.defaultDepartment,
  }};
}}

// Ported from roadlens/dedup.py:haversine_m
export function haversineM(lat1, lon1, lat2, lon2) {{
  const R = 6371000, rad = Math.PI / 180;
  const p1 = lat1 * rad, p2 = lat2 * rad;
  const dp = (lat2 - lat1) * rad, dl = (lon2 - lon1) * rad;
  const a = Math.sin(dp / 2) ** 2 + Math.cos(p1) * Math.cos(p2) * Math.sin(dl / 2) ** 2;
  return 2 * R * Math.asin(Math.sqrt(a));
}}
"""
with open(OUT, "w", encoding="utf-8") as fh:
    fh.write(js)
print(f"wrote {OUT} ({len(js.splitlines())} lines)")
