"""
Emit dashboard/ml.generated.js — the cost model, runnable in the browser.

dashboard/scan.js already runs YOLOv8-seg client-side, so a photo dropped on
the Scan tab never leaves the machine. A cost estimate that had to round-trip
to a server would break that, and would make the hosted GitHub Pages console
show nothing at all. A gradient-boosted ensemble is a few hundred small
integer/float nodes, so it ships.

Only the cost model is exported. The degradation and repair-failure models
need a defect's sighting history and a crew's repair record — data the
browser does not have and should not be handed — so those stay server-side
and the dashboard fetches them from /api/ml/* when an API is configured.

tests/test_ml_js_parity.py runs the output under node and asserts it agrees
with roadlens.ml.CostModel to 1e-9 on thousands of random tickets, the same
standard tests/test_js_parity.py holds the severity rules to.
"""
from __future__ import annotations

import json
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from roadlens.ml.registry import MODEL_DIR, ModelRegistry   # noqa: E402

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(ROOT, "dashboard", "ml.generated.js")


def main() -> int:
    registry = ModelRegistry.load(MODEL_DIR)
    if registry is None:
        print(f"No models in {MODEL_DIR}. Run `python tools/train_models.py` first.",
              file=sys.stderr)
        return 1

    payload = {
        "model": registry.cost.to_dict(),
        "provenance": registry.provenance,
        "isSynthetic": registry.provenance.get("training_data") == "synthetic_bootstrap",
    }

    js = f"""// GENERATED by tools/generate_ml_js.py — do not edit by hand.
// The cost model from roadlens/ml/models.py, exported so the browser can price
// a defect with no server, the same way dashboard/scan.js detects one.
// tests/test_ml_js_parity.py runs predictCost() below under node and asserts it
// matches roadlens.ml.CostModel.predict to 1e-9.
import {{ assess }} from './rules.generated.js';

export const COST_MODEL = {json.dumps(payload, separators=(",", ":"))};

// Ported from roadlens/ml/features.py:MONSOON_MONTHS
const MONSOON_MONTHS = new Set([6, 7, 8, 9, 10, 11]);
const OTHER = '__other__';
const DEFAULT_ROAD_CLASS = 'arterial';

// Ported from roadlens/ml/features.py:_finite. A null from a nullable column
// must become 0, not NaN: every `x < threshold` against NaN is false, so a NaN
// would silently send the row down the right branch at every split.
function finite(v) {{
  const f = Number(v);
  return Number.isFinite(f) ? f : 0;
}}

// Ported from roadlens/ml/features.py:cost_row
function costRow(ticket, rulesCost) {{
  // Python parses the ISO timestamp as UTC and reads .month; getUTCMonth is
  // 0-based, so the +1 is what makes the monsoon flag agree.
  const created = new Date(ticket.created_at || 0);
  const month = Number.isNaN(created.getTime()) ? new Date().getUTCMonth() + 1
                                                : created.getUTCMonth() + 1;
  return {{
    area_ratio: ticket.area_ratio,
    confidence: ticket.confidence,
    sightings: Math.min(finite(ticket.sightings || 1), 20),
    severity_level: ticket.severity_level,
    priority_score: ticket.priority_score,
    recurrence_count: ticket.recurrence_count || 0,
    is_monsoon: MONSOON_MONTHS.has(month) ? 1 : 0,
    log_rules_cost: Math.log(Math.max(rulesCost, 1)),
    defect_type: ticket.defect_type,
    road_class: ticket.road_class || DEFAULT_ROAD_CLASS,
  }};
}}

// Ported from roadlens/ml/features.py:FeatureSpec.vector
function vectorize(spec, row) {{
  const out = [];
  for (const name of spec.numeric) out.push(finite(row[name] ?? 0));
  for (const [name, vocab] of Object.entries(spec.categorical)) {{
    const onehot = new Array(vocab.length + 1).fill(0);
    const i = vocab.indexOf(row[name]);
    onehot[i >= 0 ? i : vocab.length] = 1;
    out.push(...onehot);
  }}
  return out;
}}

// Ported from roadlens/ml/gbt.py:RegressionTree.predict.
// Nodes are [feature, threshold, left, right, value]; feature < 0 marks a leaf.
function treeValue(nodes, x) {{
  let i = 0;
  while (nodes[i][0] >= 0) {{
    const [f, t, l, r] = nodes[i];
    i = x[f] < t ? l : r;
  }}
  return nodes[i][4];
}}

// Ported from roadlens/ml/gbt.py:GradientBoostedTrees.decision_function
function decisionFunction(gbt, x, baseScore) {{
  let out = baseScore;
  for (const tree of gbt.trees) out += gbt.learning_rate * treeValue(tree.nodes, x);
  return out;
}}

/**
 * Predict a repair cost. Mirrors roadlens.ml.CostModel.predict, including its
 * cold-start behaviour: with no trained ensemble it returns the rules-engine
 * estimate and says so, rather than inventing a number.
 */
export function predictCost(ticket) {{
  const rules = assess(ticket.defect_type, ticket.area_ratio,
                       ticket.confidence, ticket.sightings).est_cost_inr;
  const cost = COST_MODEL.model;
  const gbt = cost.gbt;

  if (!gbt) {{
    return {{
      predicted_inr: Math.round(rules), low_inr: null, high_inr: null,
      rules_inr: Math.round(rules), source: 'rules',
      note: (cost.metrics || {{}}).status || 'cold_start',
    }};
  }}

  const x = vectorize(cost.spec, costRow(ticket, rules));
  const predLog = decisionFunction(gbt, x, Math.log(Math.max(rules, 1)));
  const q = cost.conformal_q;
  const hasInterval = q !== null && q !== undefined && Number.isFinite(q);

  return {{
    predicted_inr: Math.round(Math.exp(predLog)),
    low_inr: hasInterval ? Math.round(Math.exp(predLog - q)) : null,
    high_inr: hasInterval ? Math.round(Math.exp(predLog + q)) : null,
    rules_inr: Math.round(rules),
    delta_vs_rules_pct: Math.round((Math.exp(predLog) / rules - 1) * 1000) / 10,
    interval_level: Math.round((1 - cost.alpha) * 1000) / 1000,
    source: 'model',
    is_synthetic_model: COST_MODEL.isSynthetic,
  }};
}}

/** Provenance for the dashboard's badge — never let a synthetic model pass as real. */
export function costModelStatus() {{
  return {{
    trained: Boolean(COST_MODEL.model.gbt),
    isSynthetic: COST_MODEL.isSynthetic,
    provenance: COST_MODEL.provenance,
    metrics: COST_MODEL.model.metrics || {{}},
  }};
}}
"""
    with open(OUT, "w", encoding="utf-8") as fh:
        fh.write(js)
    print(f"wrote {OUT} ({len(js) // 1024} KB, {len(js.splitlines())} lines)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
